#release configuration
#Fri Jul 24 12:53:20 CEST 2026
completedPhase=create-backup-poms
exec.pomFileName=pom.xml
exec.snapshotReleasePluginAllowed=false
pinExternals=false
preparationGoals=clean verify
project.scm.io.github.pgatzka\:example.connection=scm\:git\:https\://github.com/pgatzka/example-maven.git
project.scm.io.github.pgatzka\:example.developerConnection=scm\:git\:ssh\://git@github.com/pgatzka/example-maven.git
project.scm.io.github.pgatzka\:example.tag=HEAD
project.scm.io.github.pgatzka\:example.url=https\://github.com/pgatzka/example-maven
projectVersionPolicyConfig=<projectVersionPolicyConfig>${projectVersionPolicyConfig}</projectVersionPolicyConfig>\n
projectVersionPolicyId=defualt
pushChanges=true
releaseStrategyId=default
remoteTagging=true
scm.branchCommitComment=@{prefix} prepare branch @{releaseLabel}
scm.commentPrefix=[maven-release-plugin] 
scm.developmentCommitComment=@{prefix} prepare for next development iteration
scm.releaseCommitComment=@{prefix} prepare release @{releaseLabel}
scm.rollbackCommitComment=@{prefix} rollback the release of @{releaseLabel}
scm.tagNameFormat=@{project.artifactId}-@{project.version}
scm.url=scm\:git\:ssh\://git@github.com/pgatzka/example-maven.git
